### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by ocgltd** [idatum/labrfcat#2]
Did you figure out the REVERSE command to the minka aire fan?

Also, can you expand a bit on the upper & lower lamp control?  Does your command send a step?  Do the toggle full on/off?

**Comment by idatum** [comment]
My remote control doesn't have a reverse button, so I couldn't decode that.

I did not implement a way to dim the lamp. I could try it, but I don't use the dimming feature because the LED lamp doesn't really dim effectively. I'll give it a try when I get a chance though.

**Comment by idatum** [comment]
Light1/light2 will dim if you hold them down, it just hasn't been that useful in my experience. What I couldn't figure out using remote is what the difference between those buttons were. It might be just my model.

I updated the description, thanks.
