### ISSUE TITLE
Different DIP switches?

### ISSUE THREAD

**Issue by ocgltd** [idatum/labrfcat#5]
I'm trying to control my minka aire fan with little success (using the YS1).  I just replaced my canopy receiver (after it failed) and have the new one in place working fine with the minka remote.

I cracked open the case on the old receiver and confirmed I have only a single bank of (4) DIP switches.  The bank is labelled "SW1".  Obviously there are different minka aire transmitters and receivers.  But I suspect your code might work with some hacking.  (I would upload a photo but I don't think github supports that).

Can you confirm your individual SW8/9 switches map to 010 for off, and 110 for on.  Is that right?

Although a bit outside of the project, can you share some commands that I might use to capture a packet for a Light1 toggle command?  (from the YS1)  Then perhaps I can map it to your packet structure.

**Comment by idatum** [comment]
You might want to start with a change to the packet bits to only include SW1. 

Yes, those bits are correct for sending through rflib for off/on.

Take a look at my notes in README.md. I used gnuradio and a pretty generic RTL-SDR USB receiver. I'll try to find the gnuradio configuration file and add it to the repo. It's generally straight forward though, and gnuradio is only one option. If I recall (been awhile), I captured in gnuradio, viewed the chart (what I show in the README), then made changes to use rflib on an RPi3 with the Yard Stick One; repeated until I got it right.
